<?xml version="1.0"?>
<package format="3">
  <name>common</name>
  <version>0.0.0</version>
  <description>common</description>

  <maintainer email="wdingae@todo.com">HKUST_UAV_GROUP</maintainer>
  <license>TODO</license>

  <!-- ament 及 common 公共头/库当前声明的直接依赖。 -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclpy</depend>
  <depend>visualization_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>Eigen3</depend>
  <depend>glog</depend>
  <depend>opencv</depend>
  <depend>protobuf</depend>


  <!-- ament 构建类型，并把 materials 目录注册为包资源。 -->
  <export>
    <build_type>ament_cmake</build_type>
    <material>materials</material>
  </export>
</package>
