<?xml version="1.0"?>
<package format="3">
  <name>vehicle_msgs</name>
  <version>0.0.1</version>
  <description>Vehicle messages for ROS 2</description>
  <maintainer email="uav.ust.hk@todo.com">HKUST_UAV_GROUP</maintainer>
  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>rosidl_default_generators</buildtool_depend>

  <!-- 当前声明的几何、导航和 common 依赖。 -->
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>common</depend>
  <!-- rosidl 生成和运行时依赖。 -->
  <build_depend>rosidl_default_generators</build_depend>
  <depend>rosidl_default_runtime</depend>
  <!-- 声明为 ROS2 interface package。 -->
  <member_of_group>rosidl_interface_packages</member_of_group>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
