<?xml version="1.0"?>
<package format="3">
  <name>phy_simulator</name>
  <version>0.0.0</version>
  <description>phy_simulator</description>
  <maintainer email="wdingae@todo.com">HKUST_UAV_GROUP</maintainer>
  <license>TODO</license>

  <!-- 标准 ament_cmake 构建工具。 -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- 当前 manifest 显式声明的运行/编译依赖。 -->
  <depend>rclcpp</depend>
  <depend>rclpy</depend>
  <depend>vehicle_msgs</depend>
  <depend>common</depend>
  <depend>vehicle_model</depend>
  <exec_depend>ros2launch</exec_depend>

  <!-- 声明标准 ament_cmake 构建类型。 -->
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
